name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set environment variable
        run: |
          echo $(poetry run poetry env info --path)/bin >> $GITHUB_PATH

      - name: Install packages
        run: |
          make install-all

      - name: Show installed packages
        run: |
          poetry show
          poetry show --tree

      - name: check flamme.analyzer
        run: |
          python -c "from flamme import analyzer"
      - name: check flamme.plot
        run: |
          python -c "from flamme import plot"
      - name: check flamme.plot.utils
        run: |
          python -c "from flamme.plot import utils"
      - name: check flamme.reporter
        run: |
          python -c "from flamme import reporter"
      - name: check flamme.schema
        run: |
          python -c "from flamme import schema"
      - name: check flamme.schema.reader
        run: |
          python -c "from flamme.schema import reader"
      - name: check flamme.section
        run: |
          python -c "from flamme import section"
      - name: check flamme.utils
        run: |
          python -c "from flamme import utils"
      - name: check flamme.utils.data
        run: |
          python -c "from flamme.utils import data"
